### ISSUE TITLE
Equation (TeX) rendering problem in notes

### ISSUE THREAD

**Issue by BaksiLi** [BaksiLi/CS-Hypomnema#1]
I am the author.

This issue is to gather ideas for equation rendering in the notes.

So far what I do is just keep these LaTeX equations there; and probably in the future, convert notes into HTML for viewing.

What do you think?

**Comment by Eldembu** [comment]
I discovered this [Common Flavoured Markdown Converter](https://github.com/CyC2018/GFM-Converter) which may help.

**Comment by BaksiLi** [comment]
> I discovered this [Common Flavoured Markdown Converter](https://github.com/CyC2018/GFM-Converter) which may help.

I found [readme2tex](https://github.com/leegao/readme2tex), somehow similar to your discovery.

I will have a study of them and to work on solving the problem soon.

Thanks!
